from django.core.exceptions import ValidationError


def validate_email_via_emailhunter(value):
    # raise ValidationError("Emailhunter validation failed")
    return value
